config/routes.rb
Rails.application.routes.draw do
  root 'rooms#index'
  resources :rooms do # only [:index, :show ]
    resources :orders, only: [:new, :create]
  end
  resources :users, except: [:index] do
    resources :rooms, only: [:new, :create, :edit, :update]
    resources :orders, only: [:index]
  end

  resource :session, only: [:new, :create, :destroy]

  resources :orders, except: [:show]

end

app/models/order.rb
class Order < ActiveRecord::Base
	belongs_to :room
	belongs_to :user

	validates :check_in, presence: true
	validates :check_out, presence: true
end

app/models/room.rb
class Room < ActiveRecord::Base
	belongs_to :user
	has_many :orders

	validates :price_in_pence, presence: true, :numericality => { :greater_than_or_equal_to => 0 }
	validates :name, presence: true
	validates :address, presence: true
	validates :longitude, presence: true
	validates :latitude, presence: true

	geocoded_by :address
	before_validation :geocode
end

app/models/user.rb
class User < ActiveRecord::Base
	has_secure_password
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_user, :current_user?

  def current_user
  	if session[:user_id].present?
  		User.find(session[:user_id])
  	end
  end


  def current_user?
  	current_user.present?
  end

  def require_user
  	if current_user?
  		current_user
  	else
  		flash[:error] = "Sorry, you are not signed in"
  		redirect_to new_session_path
  	end
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :find_room, except: [:index]

  def index
  	@orders = Order.all
  end
  def new
  	@order = Order.new
  end

  def create
  	@order = Order.new(order_params)
  	@order.user = current_user
  	@order.room = @room
  	if @order.save
  		Stripe.api_key = 'sk_test_5b4UqeUT48FGf5Sg3kqXIG0q'
		 Stripe::Charge.create(
		  :amount => @order.room.price_in_pence,
		  :currency => "usd",
		  :card => @order.stripe_token, # obtained with Stripe.js
		  :description => "Charge for #{@order.user.email}"
		)
		flash[:success] = "Order created"
  		redirect_to user_orders_path(current_user)
  	else
  		flash[:error] = "Sorry, no room at the inn"
  		flash[:more] = @order.errors.full_messages
  		render :new
  	end
 end

  private
  def order_params
  	params.require(:order).permit(:check_in,:check_out,:stripe_token,:user_id,:room_id)
  end
  def find_room
  	@room = Room.find(params[:room_id])
  end
end

app/controllers/rooms_controller.rb
class RoomsController < ApplicationController

  before_action :set_locale
  before_action :find_room, only: [:edit,:show,:update]
  before_action :require_user, except: [:index,:show]
 
  def index
  	if params[:search] and params[:search][:query]
  		@rooms = [{:name => 'My search result'}]
  		if @rooms.any?
  			flash.now[:success] = 'Rooms matching #{rooms.size}'
  		else
  			flash.now[:warning] = 'Sorry, no matching rooms here'
  		end
  	else
  		@rooms = Room.all
  	end
  end

  def show
  end

  def new
  	@room = Room.new
  end

  def create
  	@room = Room.new(room_params)
  	@room.user = current_user
  	if @room.save
  		flash[:success] = "Room created"
  		redirect_to rooms_path
  	else
  		flash[:error] = "Sorry, no room at the inn"
  		render :new
  	end
  end

  def edit
  	@room = Room.find(params[:id])
  	@user = User.find(current_user.id)
  	if ! @room
  		flash[:errors] = "No room"
  	end
  end

  def update
    if @room
      if @room.update(room_params)
        flash[:success] = @room.name + " updated"
      else
        flash[:error] = @room.name + " could not be updated"
        @room.errors.full_messages.each do | message |
          flash[:error] << "\n" + message
        end
        render :edit
       end
    else
      flash[:warning] = @room.id + " could not be found, not updated"
      render :edit
    end
    redirect_to rooms_path
  end

  def destroy
  	room = Room.find(params[:id])
  	if room
  		if room.delete
  			flash[:success] = room.name + " deleted"
  		else
  			flash[:error] = room.name + " could not be deleted"
  			room.errors.full_messages.each do | message |
  				flash[:error] << "\n" + message
  			end
  		end
  	else
  		flash[:warning] = room.name + " could not be found, not deleted"
  		render :edit
  	end
  	redirect_to rooms_path
  end

  private
  def room_params
  	params.require(:room).permit( 
  		:price_in_pence, 
  		:name, 
  		:description, 
  		:availability, 
  		:latitude, 
  		:longitude, 
  		:phone_no, 
  		:no_of_rooms, 
  		:max_guests, 
  		:pets, 
  		:address)
  end

  def find_room
  	@room = Room.find(params[:id])
  end

  def set_locale
    I18n.locale = request.env['HTTP_ACCEPT_LANGUAGE'].scan(/^[a-zA-Z-]+[^,]/).first || I18n.default_locale
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
	def new
	end
	def create
		login = session_params
		user = User.find_by(:name => login[:name])
		if user.present? and user.authenticate(login[:password])
			flash[:success] = "found"
			reset_session
			session[:user_id] = user.id
			redirect_to rooms_path
		else
			flash[:error] = "No matching details for " + login[:name]
			render :new
		end
	end
	def destroy
		reset_session
		redirect_to rooms_path
	end

	private
	def session_params
		params.require(:session).permit(:name,:password)
	end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  	@user = User.new
  end

  def create 
  	@user = User.new(user_params)
  	if @user.save
  		flash[:success] = "User created"
  		redirect_to rooms_path
  	else
  		flash[:error] = "Sorry, no room at the inn"
  		flash[:error] = @user.name + " could not be created"
  		@user.errors.full_messages.each do | message |
  			flash[:error] << "\n" + message
  		end
  		render :new
  	end
  end

  def edit
  	@user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user
      if @user.update(user_params)
        flash[:success] = @user.name + " updated"
      else
        flash[:error] = @user.name + " could not be updated"
        @user.errors.full_messages.each do | message |
          flash[:error] << "\n" + message
        end
        render :edit
       end
    else
      flash[:warning] = @user.name + " could not be found, not updated"
      render :edit
    end
    redirect_to rooms_path

  end

  def show
  	@user = User.find(params[:id])
  end


  def destroy
  	user = User.find(params[:id])
  	if user
  		if user.delete
  			flash[:success] = user.name + " deleted"
  		else
  			flash[:error] = user.name + " could not be deleted"
  			user.errors.full_messages.each do | message |
  				flash[:error] << "\n" + message
  			end
  		end
  	else
  		flash[:warning] = user.name + " could not be found, not deleted"
  		render :edit
  	end
  	redirect_to rooms_path
  end

  def user_params
  	params.require(:user).permit(:name,:email,:password,:password_confirmation)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/rooms_helper.rb
module RoomsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/layouts/application.html.erb
<!doctype html>
<html>
<head>
  <title>Onboard</title>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
  <script type="text/javascript" src="https://js.stripe.com/v2/"></script>
  <script type="text/javascript">
    // This identifies your website in the createToken call below
    Stripe.setPublishableKey('pk_test_dVcAYg8GCyNtREylJTn624Rw');
    // ...
    jQuery(function($) {
  $('#new_order').submit(function(event) {
    var $form = $(this);

    // Disable the submit button to prevent repeated clicks
    $form.find('button').prop('disabled', true);

    Stripe.card.createToken($form, stripeResponseHandler);

    // Prevent the form from submitting with the default action
    return false;
  });
  function stripeResponseHandler(status, response) {
  var $form = $('#new_order');

  if (response.error) {
    // Show the errors on the form
    $form.find('.payment-errors').text(response.error.message);
    $form.find('button').prop('disabled', false);
  } else {
    // response contains id and card, which contains additional card details
    var token = response.id;
    // Insert the token into the form so it gets submitted to the server
    $form.append($('<input type="hidden" name="order[stripe_token]" />').val(token));
    // and submit
    $form.get(0).submit();
  }
};
});
  </script></head>
<body>

<div class="container">
  <header class="row">
    <h1 class="two columns">
      <%= link_to rooms_path do %>
        <%= image_tag "logo.png" %>
      <% end %>
    </h1>
    <div class="three columns">
    <%= simple_form_for :search, method: :get do |search| %>
      <%= search.input :query, label: false %>
    <% end %>
    </div>

    <nav class="seven columns">

      <% if current_user? %>
        <%= current_user.name %>
        <%= link_to "Dashboard", user_path(current_user) %>
        <%= link_to "Add a room", new_user_room_path(current_user) %>
        <%= link_to "Orders", orders_path(current_user) %>
        <%= link_to "Sign out", session_path(@session), method: :delete, data: { confirm: 'Are you sure?' } %>
      <% else %>
        <%= link_to "Sign up", new_user_path %>
        <%= link_to "Sign in",new_session_path %>
      <% end %>
    </nav>
  </header>

  <% if ! flash.empty? %>
   <% flash.each do | key, value | %>
  <div class="flash <%=key%>"><%= value %><hr /></div>
    <% end %>
  <% end %>
  </div>
  <article class="row">
    <%= yield %>
  </article>

  <footer>
    <p>&copy; <%= Date.today.year %> Onboard Ltd</p>
  </footer>
</div>

</body>
</html>

app/views/orders/create.html.erb
<h1>Orders#create</h1>
<p>Find me in app/views/orders/create.html.erb</p>

app/views/orders/index.html.erb
<ul>
	<%= @orders.each do | order | %>
<li><%= order.inspect %></li>
<% end %>
</ul>

app/views/orders/new.html.erb
<%= simple_form_for @order, url: room_orders_path, method: 'post' do | form |%>
<%= form.input :check_in %>
<%= form.input :check_out %>
  <span class="payment-errors"></span>

  <div class="form-row">
    <label>
      <span>Card Number</span>
      <input type="text" size="20" data-stripe="number"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>CVC</span>
      <input type="text" size="4" data-stripe="cvc"/>
    </label>
  </div>

  <div class="form-row">
    <label>
      <span>Expiration (MM/YYYY)</span>
      <input type="text" size="2" data-stripe="exp-month"/>
    </label>
    <span> / </span>
    <input type="text" size="4" data-stripe="exp-year"/>
  </div>

  <button type="submit">Submit Payment</button>
<% end %>

app/views/rooms/_form.html.erb
<section>
	<fieldset>
<%= simple_form_for [@user, @room] do |form| %>
  <%= form.input :price_in_pence %>
  <%= form.input :name %>
  <%= form.input :description %>
  <%= form.input :availability %>
  <%= form.input :address %>
  <%# form.input :latitude %>
  <%# form.input :longitude %>
  <%= form.input :phone_no %>
  <%= form.input :no_of_rooms %>
  <%= form.input :max_guests %>
  <%= form.input :pets %>
  <%# form.input :user_id %>
  <%= form.button :submit %>

<% end %>
</fieldset>
</section>

app/views/rooms/edit.html.erb
<%= render "form" %>

app/views/rooms/index.html.erb
<% @rooms.each do | room | %>
<section>
	<h2><%= link_to room.name, room_path(room.id) %></h2>
	<p><span class='fieldlabel'>Room rate:</span>
		<span class="fieldValue"><%= number_to_currency room.price_in_pence %></span>
	</p>
</section>
<% end %>
<%= link_to "New", new_room_path, class: 'button' %>

app/views/rooms/new.html.erb
<%= render "form" %>

app/views/rooms/show.html.erb
<section>
	<h2><%= @room.name %></h2>
	<div class="address">
		<p><%= @room.address %></p>
	</div>
	<div class="image">
	</div>
	<div class="map" data-lat="<%=@room.latitude%>" data-lng="<%=@room.longitude%>">
		<%# Geocoder adds automatically %>
	</div>
	<p><span class='fieldlabel'>Room rate:</span>
		<span class="fieldValue"><%= number_to_currency @room.price_in_pence %></span>
	</p>
	<div class="description"><%= simple_format @room.description %></div>

	<p>Ask <%= mail_to @room.user.email, @room.user.name %> about this room</p>
	<div class="actions">
		<% if current_user? %>
			<% if current_user.id == @room.user.id %>
				<p><%= link_to "Edit", edit_user_room_path(current_user, @room) %></p>
				<p><%= link_to "Delete", room_path(@room), method: :delete, data: { confirm: 'Are you sure?' } %></p>
			<% else %>
				<p><%= link_to "Book this room", new_room_order_path(@room) %></p>
			<% end %>
		<% else %>
			<p> <%= link_to "Sign up to book this room", new_user_path, class: :button %> </p
		<% end %>
	</div>
</section>

app/views/users/_form.html.erb
<section>
	<fieldset>
		<%= simple_form_for @user do | form | %>
		  <%= form.input :name %>
		  <%= form.input :email %>
		  <%= form.input :password %>
		  <%= form.input :password_confirmation %>
		  <%= form.button :submit %>

		<% end %>
	</fieldset>
</section>

app/views/users/edit.html.erb
<%= render "form" %>

app/views/users/new.html.erb
<%= render "form" %>

app/views/users/show.html.erb
<h2><%= @user.name %></h2>
<p><%= @user.email %></p>
<div class="actions">
	<p><%= link_to "Edit", edit_user_path(@user) %></p>
	<p><%= link_to "Delete", user_path(@user), method: :delete, data: { confirm: 'Are you sure?' } %></p>
</div>